total_episodes: 2000
learning_rate: 0.001
gamma: 0.95
epsilon_start: 0.8
epsilon_end: 0.05
epsilon_decay: 500
n_runs: 5
seed: 123
max_memory: 100000
batch_size: 1000
target_update_freq: 10
map_size: 8
action_size: 4
state_size: [8, 8, 5]