total_episodes: 2000    
n_runs: 5                 
batch_size: 64             
n_epochs: 4               
N: 20                      
learning_rate: 0.0003
gamma: 0.99                
gae_lambda: 0.95           
policy_clip: 0.2           
n_actions: 2               
seed: 123                  
map_size: 8
action_size: 4
state_size: [8, 8, 5]